from __future__ import annotations

from dataclasses import dataclass
import hashlib
import gzip
import pickle
from pathlib import Path
import struct
import tarfile
import urllib.request

import numpy as np


CIFAR10_URL = "https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz"
CIFAR10_MD5 = "c58f30108f718f92721af3b95e74349a"
CIFAR10_LABELS = (
    "airplane", "automobile", "bird", "cat", "deer",
    "dog", "frog", "horse", "ship", "truck",
)
FASHION_MNIST_LABELS = (
    "t-shirt/top", "trouser", "pullover", "dress", "coat",
    "sandal", "shirt", "sneaker", "bag", "ankle boot",
)
FASHION_MNIST_BASE = (
    "https://raw.githubusercontent.com/zalandoresearch/fashion-mnist/master/"
    "data/fashion"
)
FASHION_MNIST_FILES = {
    "train-images-idx3-ubyte.gz": "8d4fb7e6c68d591d4c3dfef9ec88bf0d",
    "train-labels-idx1-ubyte.gz": "25c81989df183df01b3e8a0aad5dffbe",
    "t10k-images-idx3-ubyte.gz": "bef4ecab320f06d8554ea6380940ec79",
    "t10k-labels-idx1-ubyte.gz": "bb300cfdad3c16e7a12a480ee83cd310",
}


@dataclass(frozen=True)
class MultimodalSplit:
    images: np.ndarray
    questions: np.ndarray
    answers: np.ndarray


VisualShapesSplit = MultimodalSplit


@dataclass(frozen=True)
class MultimodalData:
    train: MultimodalSplit
    validation: MultimodalSplit
    test: MultimodalSplit
    answer_names: tuple[str, ...]
    question_names: tuple[str, ...]
    name: str
    source: str
    license: str
    evaluation_tier: str


VisualShapesData = MultimodalData


def load_multimodal_data(
    dataset: str,
    dataset_dir: Path | None = None,
    allow_network: bool = True,
    maximum_examples: int | None = None,
) -> MultimodalData:
    if dataset == "visual-shapes":
        return load_visual_shapes()
    if dataset == "cifar10-qa":
        if dataset_dir is None:
            raise ValueError("cifar10-qa requires dataset_dir")
        return load_cifar10_qa(dataset_dir, allow_network, maximum_examples)
    if dataset == "fashion-mnist-qa":
        if dataset_dir is None:
            raise ValueError("fashion-mnist-qa requires dataset_dir")
        return load_fashion_mnist_qa(dataset_dir, allow_network, maximum_examples)
    raise ValueError(f"unknown multimodal dataset: {dataset}")


def load_visual_shapes(seed: int = 2026) -> MultimodalData:
    """Build a deterministic, fully local image-question benchmark."""
    rng = np.random.default_rng(seed)
    splits = [_render_split(rng, size) for size in (480, 120, 120)]
    return MultimodalData(
        *splits,
        answer_names=(
            "red", "green", "blue", "square", "cross",
            "top-left", "top-right", "bottom-left", "bottom-right",
        ),
        question_names=("what colour?", "what shape?", "where is it?"),
        name="visual-shapes",
        source="locally rendered deterministic images",
        license="generated by this project",
        evaluation_tier="l0_synthetic",
    )


def load_cifar10_qa(
    dataset_dir: Path,
    allow_network: bool = True,
    maximum_examples: int | None = None,
    seed: int = 2026,
) -> MultimodalData:
    """Load official CIFAR-10 pixels as a reproducible L1 visual QA task."""
    root = Path(dataset_dir) / "cifar10"
    extracted = root / "cifar-10-batches-py"
    if not _cifar_files_present(extracted):
        archive = root / "cifar-10-python.tar.gz"
        if not archive.exists():
            if not allow_network:
                raise FileNotFoundError(
                    f"CIFAR-10 is not cached at {extracted}; rerun once without --offline"
                )
            root.mkdir(parents=True, exist_ok=True)
            temporary = archive.with_suffix(".download")
            _download_with_resume(CIFAR10_URL, temporary)
            temporary.replace(archive)
        if _md5(archive) != CIFAR10_MD5:
            raise ValueError(f"CIFAR-10 archive checksum mismatch: {archive}")
        _safe_extract(archive, root)
    train_images, train_labels = _read_cifar_batches(
        [extracted / f"data_batch_{index}" for index in range(1, 6)]
    )
    test_images, test_labels = _read_cifar_batches([extracted / "test_batch"])
    rng = np.random.default_rng(seed)
    validation_size = min(1000, max(10, len(train_labels) // 5))
    validation_indices = _stratified_indices(train_labels, validation_size, rng)
    remaining = np.setdiff1d(np.arange(len(train_labels)), validation_indices)
    train_limit = min(len(remaining), maximum_examples or 5000)
    local_indices = _stratified_indices(train_labels[remaining], train_limit, rng)
    train_indices = remaining[local_indices]
    test_indices = _stratified_indices(test_labels, min(1000, len(test_labels)), rng)
    return MultimodalData(
        _classification_split(train_images[train_indices], train_labels[train_indices]),
        _classification_split(train_images[validation_indices], train_labels[validation_indices]),
        _classification_split(test_images[test_indices], test_labels[test_indices]),
        answer_names=CIFAR10_LABELS,
        question_names=("what object is shown?",),
        name="cifar10-qa",
        source=CIFAR10_URL,
        license="CIFAR-10 research dataset; see dataset website",
        evaluation_tier="l1_public_images",
    )


def load_fashion_mnist_qa(
    dataset_dir: Path,
    allow_network: bool = True,
    maximum_examples: int | None = None,
    seed: int = 2026,
) -> MultimodalData:
    """Load official Fashion-MNIST as a small, cacheable public image QA task."""
    root = Path(dataset_dir) / "fashion-mnist" / "raw"
    root.mkdir(parents=True, exist_ok=True)
    for filename, checksum in FASHION_MNIST_FILES.items():
        path = root / filename
        if not path.exists():
            if not allow_network:
                raise FileNotFoundError(
                    f"Fashion-MNIST is not cached at {root}; rerun once without --offline"
                )
            partial = path.with_suffix(path.suffix + ".download")
            _download_with_resume(f"{FASHION_MNIST_BASE}/{filename}", partial)
            partial.replace(path)
        if _md5(path) != checksum:
            raise ValueError(f"Fashion-MNIST checksum mismatch: {path}")
    train_images = _read_idx_images(root / "train-images-idx3-ubyte.gz")
    train_labels = _read_idx_labels(root / "train-labels-idx1-ubyte.gz")
    test_images = _read_idx_images(root / "t10k-images-idx3-ubyte.gz")
    test_labels = _read_idx_labels(root / "t10k-labels-idx1-ubyte.gz")
    rng = np.random.default_rng(seed)
    validation_indices = _stratified_indices(train_labels, 1000, rng)
    remaining = np.setdiff1d(np.arange(len(train_labels)), validation_indices)
    train_limit = min(len(remaining), maximum_examples or 5000)
    local_indices = _stratified_indices(train_labels[remaining], train_limit, rng)
    test_indices = _stratified_indices(test_labels, min(1000, len(test_labels)), rng)
    return MultimodalData(
        _classification_split(train_images[remaining[local_indices]], train_labels[remaining[local_indices]]),
        _classification_split(train_images[validation_indices], train_labels[validation_indices]),
        _classification_split(test_images[test_indices], test_labels[test_indices]),
        answer_names=FASHION_MNIST_LABELS,
        question_names=("what fashion item is shown?",),
        name="fashion-mnist-qa",
        source="https://github.com/zalandoresearch/fashion-mnist",
        license="MIT code; Fashion-MNIST dataset citation required",
        evaluation_tier="l1_public_images",
    )
def _classification_split(images: np.ndarray, labels: np.ndarray) -> MultimodalSplit:
    return MultimodalSplit(
        images.astype(np.float32) / 255.0,
        np.zeros(len(labels), dtype=np.int64),
        labels.astype(np.int64),
    )


def _cifar_files_present(directory: Path) -> bool:
    return all(
        (directory / name).exists()
        for name in [*(f"data_batch_{i}" for i in range(1, 6)), "test_batch"]
    )


def _read_cifar_batches(paths: list[Path]) -> tuple[np.ndarray, np.ndarray]:
    images, labels = [], []
    for path in paths:
        with path.open("rb") as handle:
            payload = pickle.load(handle, encoding="bytes")
        raw = np.asarray(payload[b"data"], dtype=np.uint8)
        images.append(raw.reshape(-1, 3, 32, 32))
        raw_labels = payload[b"labels"] if b"labels" in payload else payload["labels"]
        labels.append(np.asarray(raw_labels, dtype=np.int64))
    return np.concatenate(images), np.concatenate(labels)


def _read_idx_images(path: Path) -> np.ndarray:
    with gzip.open(path, "rb") as handle:
        magic, count, rows, columns = struct.unpack(">IIII", handle.read(16))
        if magic != 2051:
            raise ValueError(f"invalid IDX image file: {path}")
        images = np.frombuffer(handle.read(), dtype=np.uint8).reshape(count, rows, columns)
    padded = np.pad(images, ((0, 0), (2, 2), (2, 2)))
    return np.repeat(padded[:, None], 3, axis=1)


def _read_idx_labels(path: Path) -> np.ndarray:
    with gzip.open(path, "rb") as handle:
        magic, count = struct.unpack(">II", handle.read(8))
        if magic != 2049:
            raise ValueError(f"invalid IDX label file: {path}")
        return np.frombuffer(handle.read(), dtype=np.uint8, count=count).astype(np.int64)


def _stratified_indices(labels: np.ndarray, size: int, rng: np.random.Generator) -> np.ndarray:
    size = min(size, len(labels))
    classes = np.unique(labels)
    base, remainder = divmod(size, len(classes))
    selected = []
    for position, label in enumerate(classes):
        candidates = np.flatnonzero(labels == label)
        take = min(len(candidates), base + (position < remainder))
        selected.extend(rng.choice(candidates, size=take, replace=False).tolist())
    if len(selected) < size:
        available = np.setdiff1d(np.arange(len(labels)), np.asarray(selected))
        selected.extend(rng.choice(available, size=size - len(selected), replace=False).tolist())
    return rng.permutation(np.asarray(selected, dtype=np.int64))


def _md5(path: Path) -> str:
    digest = hashlib.md5()  # nosec B324: upstream publishes this checksum
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _download_with_resume(url: str, target: Path) -> None:
    """Download a large public archive while preserving interrupted progress."""
    existing = target.stat().st_size if target.exists() else 0
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "auto-research-dataset-fetcher/1.0",
            "Accept": "application/octet-stream,*/*;q=0.8",
        },
    )
    if existing:
        request.add_header("Range", f"bytes={existing}-")
    with urllib.request.urlopen(request, timeout=60) as response:
        resumed = existing > 0 and getattr(response, "status", None) == 206
        mode = "ab" if resumed else "wb"
        with target.open(mode) as handle:
            for block in iter(lambda: response.read(1024 * 1024), b""):
                handle.write(block)


def _safe_extract(archive: Path, destination: Path) -> None:
    destination = destination.resolve()
    with tarfile.open(archive, "r:gz") as bundle:
        for member in bundle.getmembers():
            target = (destination / member.name).resolve()
            if destination not in target.parents and target != destination:
                raise ValueError(f"unsafe archive path: {member.name}")
        bundle.extractall(destination)  # noqa: S202 - paths validated above


def _render_split(rng: np.random.Generator, size: int) -> MultimodalSplit:
    images = np.zeros((size, 3, 32, 32), dtype=np.float32)
    questions = np.arange(size, dtype=np.int64) % 3
    answers = np.empty(size, dtype=np.int64)
    colors = np.eye(3, dtype=np.float32)
    centers = ((8, 8), (8, 24), (24, 8), (24, 24))
    for index in range(size):
        color = int(rng.integers(3))
        shape = int(rng.integers(2))
        position = int(rng.integers(4))
        row, column = centers[position]
        image = images[index]
        if shape == 0:
            image[:, row - 4:row + 4, column - 4:column + 4] = colors[color, :, None, None]
        else:
            image[:, row - 2:row + 2, column - 6:column + 6] = colors[color, :, None, None]
            image[:, row - 6:row + 6, column - 2:column + 2] = colors[color, :, None, None]
        image += rng.normal(0.0, 0.015, image.shape).astype(np.float32)
        np.clip(image, 0.0, 1.0, out=image)
        question = int(questions[index])
        answers[index] = (color, 3 + shape, 5 + position)[question]
    order = rng.permutation(size)
    return MultimodalSplit(images[order], questions[order], answers[order])
