"""Compatibility imports; implementations live in stable mechanisms modules."""

from __future__ import annotations

from auto_research.agent_research.mechanisms.proposed_action import ProposedAction
from auto_research.agent_research.mechanisms.meta_reasoning_dispatch import meta_reasoning_dispatch
from auto_research.agent_research.mechanisms.compact_artifact_state import compact_artifact_state
from auto_research.agent_research.mechanisms.apply_context_file import apply_context_file
from auto_research.agent_research.mechanisms.suffix_cache_reuse import suffix_cache_reuse
from auto_research.agent_research.mechanisms.meta_skill_bank import MetaSkillBank
from auto_research.agent_research.mechanisms.update_branch_subsets import update_branch_subsets
from auto_research.agent_research.mechanisms.route_branch import route_branch
