"""Declarative Agent key/symbol bindings; importing this never loads implementations."""

AGENT_BINDINGS = {
    "ace-data": ("auto_research.agent_research.mechanisms.acedata_agent", "ACEDataAgent"),
    "adavdr": ("auto_research.agent_research.mechanisms.ada_v_d_r_agent", "AdaVDRAgent"),
    "agent-g2": ("auto_research.agent_research.mechanisms.agent_g2_agent", "AgentG2Agent"),
    "agent-opsd": ("auto_research.agent_research.method_families.rl", "AgentOPSDAgent"),
    "agent-r1": ("auto_research.agent_research.p1_20260808", "AgentR1Agent"),
    "agent0": ("auto_research.agent_research.p0_20260808", "Agent0Agent"),
    "agentx": ("auto_research.agent_research.mechanisms.agent_x_agent", "AgentXAgent"),
    "ahead": ("auto_research.agent_research.mechanisms.aheadagent", "AHEADAgent"),
    "arenaflow": ("auto_research.agent_research.mechanisms.arena_flow_agent", "ArenaFlowAgent"),
    "art": ("auto_research.agent_research.method_families.memory", "ARTAgent"),
    "atomrec": ("auto_research.agent_research.mechanisms.public_observation", "AtomRecAgent"),
    "auso": ("auto_research.agent_research.mechanisms.action_information", "AUSOAgent"),
    "autogen": ("auto_research.agent_research.method_families.planning", "AutoGenAgent"),
    "autosaddler": (
        "auto_research.agent_research.mechanisms.auto_saddler_agent",
        "AutoSaddlerAgent",
    ),
    "autoviewmem": (
        "auto_research.agent_research.mechanisms.auto_view_mem_agent",
        "AutoViewMemAgent",
    ),
    "cam-df": ("auto_research.agent_research.method_families.rl", "CAMDFAgent"),
    "camel": ("auto_research.agent_research.p1_20260808", "CAMELAgent"),
    "caskg": ("auto_research.agent_research.mechanisms.ca_s_k_g_agent", "CaSKGAgent"),
    "cast": ("auto_research.agent_research.method_families.rl", "CASTAgent"),
    "cera-moa": ("auto_research.agent_research.mechanisms.ceramo_a_agent", "CERAMoAAgent"),
    "cipo": ("auto_research.agent_research.mechanisms.cipoagent", "CIPOAgent"),
    "cobra-skills": (
        "auto_research.agent_research.mechanisms.cobraskills_agent",
        "COBRASkillsAgent",
    ),
    "codegrep": ("auto_research.agent_research.mechanisms.code_grep_agent", "CodeGrepAgent"),
    "coevo-mem": ("auto_research.agent_research.method_families.rl", "CoEvoMemAgent"),
    "coskill": ("auto_research.agent_research.mechanisms.public_observation", "CoSkillAgent"),
    "covemem": ("auto_research.agent_research.mechanisms.co_ve_mem_agent", "CoVeMemAgent"),
    "deeprepro": ("auto_research.agent_research.mechanisms.deep_repro_agent", "DeepReproAgent"),
    "deepresearcher": ("auto_research.agent_research.p0_20260808", "DeepResearcherAgent"),
    "dependency-refinement": (
        "auto_research.agent_research.mechanisms.dependency_refinement_agent",
        "DependencyRefinementAgent",
    ),
    "draco": ("auto_research.agent_research.mechanisms.dracoagent", "DRACOAgent"),
    "ecdysis": ("auto_research.agent_research.mechanisms.ecdysis_agent", "EcdysisAgent"),
    "envace": ("auto_research.agent_research.method_families.rl", "EnvACEAgent"),
    "evoharness-rl": (
        "auto_research.agent_research.mechanisms.evo_harness_r_l_agent",
        "EvoHarnessRLAgent",
    ),
    "evoskill-gui": (
        "auto_research.agent_research.mechanisms.evo_skill_g_u_i_agent",
        "EvoSkillGUIAgent",
    ),
    "feedback-scaffold": (
        "auto_research.agent_research.mechanisms.feedback_scaffold_agent",
        "FeedbackScaffoldAgent",
    ),
    "fuse-evaluator": (
        "auto_research.agent_research.mechanisms.fuse_evaluator_agent",
        "FuseEvaluatorAgent",
    ),
    "gaia": ("auto_research.agent_research.p1_20260808", "GAIAAgent"),
    "generative-agents": (
        "auto_research.agent_research.method_families.memory",
        "GenerativeAgentsAgent",
    ),
    "gigpo": ("auto_research.agent_research.method_families.rl", "GiGPOAgent"),
    "graphskillevo": (
        "auto_research.agent_research.mechanisms.graph_skill_evo_agent",
        "GraphSkillEvoAgent",
    ),
    "grounded-memory": (
        "auto_research.agent_research.mechanisms.grounded_memory_agent",
        "GroundedMemoryAgent",
    ),
    "grsd": ("auto_research.agent_research.method_families.rl", "GRSDAgent"),
    "gse": ("auto_research.agent_research.mechanisms.gseagent", "GSEAgent"),
    "harness-bandit": (
        "auto_research.agent_research.mechanisms.harness_bandit_agent",
        "HarnessBanditAgent",
    ),
    "harness-design-study": (
        "auto_research.agent_research.mechanisms.harness_design_study_agent",
        "HarnessDesignStudyAgent",
    ),
    "harnesslens": (
        "auto_research.agent_research.mechanisms.harness_lens_agent",
        "HarnessLensAgent",
    ),
    "harnessopt-bench": (
        "auto_research.agent_research.mechanisms.harness_opt_bench_agent",
        "HarnessOptBenchAgent",
    ),
    "hindsearch": ("auto_research.agent_research.mechanisms.hind_search_agent", "HindSearchAgent"),
    "hiskill": ("auto_research.agent_research.method_families.rl", "HiSkillAgent"),
    "hugginggpt": ("auto_research.agent_research.method_families.memory", "HuggingGPTAgent"),
    "hymem": ("auto_research.agent_research.historical_b10_b11", "HyMemAgent"),
    "hyperagent": ("auto_research.agent_research.historical_b10_b11", "HyperAgentAgent"),
    "interactive-memory": (
        "auto_research.agent_research.mechanisms.interactive_memory_agent",
        "InteractiveMemoryAgent",
    ),
    "jit-agent": ("auto_research.agent_research.mechanisms.jitagent", "JITAgent"),
    "lats": ("auto_research.agent_research.method_families.planning", "LATSAgent"),
    "legomem": ("auto_research.agent_research.method_families.memory", "LegoMemAgent"),
    "long-context": ("auto_research.agent_research.method_families.planning", "LongContextAgent"),
    "loongreflect": ("auto_research.agent_research.historical_b10_b11", "LoongReflectAgent"),
    "loop": ("auto_research.agent_research.method_families.rl", "LOOPAgent"),
    "mace": ("auto_research.agent_research.mechanisms.maceagent", "MACEAgent"),
    "manta": ("auto_research.agent_research.historical_b10_b11", "MANTAAgent"),
    "maple": ("auto_research.agent_research.mechanisms.mapleagent", "MAPLEAgent"),
    "memento-skills": ("auto_research.agent_research.p0_20260808", "MementoSkillsAgent"),
    "memforest": ("auto_research.agent_research.mechanisms.event_tree", "MemForestAgent"),
    "memgpt": ("auto_research.agent_research.method_families.memory", "MemGPTAgent"),
    "memorycpt": ("auto_research.agent_research.mechanisms.memory_c_p_t_agent", "MemoryCPTAgent"),
    "memskill": ("auto_research.agent_research.p0_20260808", "MemSkillAgent"),
    "memtool": ("auto_research.agent_research.method_families.memory", "MemToolAgent"),
    "mrkl": ("auto_research.agent_research.method_families.memory", "MRKLAgent"),
    "mua-rl": ("auto_research.agent_research.method_families.rl", "MUARLAgent"),
    "multi-harness-rl": (
        "auto_research.agent_research.mechanisms.public_observation",
        "MultiHarnessRLAgent",
    ),
    "ocsd": ("auto_research.agent_research.method_families.rl", "OCSDAgent"),
    "openloopevolve": ("auto_research.agent_research.historical_b10_b11", "OpenLoopEvolveAgent"),
    "pal": ("auto_research.agent_research.method_families.memory", "PALAgent"),
    "pearl": ("auto_research.agent_research.method_families.planning", "PEARLAgent"),
    "planpo": ("auto_research.agent_research.historical_b10_b11", "PlanPOAgent"),
    "pmcoder": ("auto_research.agent_research.historical_b10_b11", "PMCoderAgent"),
    "procedural-graphs": (
        "auto_research.agent_research.mechanisms.procedural_graph_agent",
        "ProceduralGraphAgent",
    ),
    "progrouter": ("auto_research.agent_research.mechanisms.prog_router_agent", "ProgRouterAgent"),
    "prompts": ("auto_research.agent_research.mechanisms.promptsagent", "PROMPTSAgent"),
    "ragen": ("auto_research.agent_research.method_families.rl", "RAGENAgent"),
    "react": ("auto_research.agent_research.method_families.planning", "ReActAgent"),
    "redevoagent": ("auto_research.agent_research.mechanisms.red_evo_agent", "RedEvoAgent"),
    "reflexion": ("auto_research.agent_research.method_families.planning", "ReflexionAgent"),
    "repoatlas": ("auto_research.agent_research.mechanisms.repo_atlas_agent", "RepoAtlasAgent"),
    "retool": ("auto_research.agent_research.p0_20260808", "ReToolAgent"),
    "rewoo": ("auto_research.agent_research.method_families.planning", "ReWOOAgent"),
    "rtpo": ("auto_research.agent_research.historical_b10_b11", "RTPOAgent"),
    "sage": ("auto_research.agent_research.p0_20260808", "SAGEAgent"),
    "sapo": ("auto_research.agent_research.historical_b10_b11", "SAPOAgent"),
    "saycan": ("auto_research.agent_research.method_families.memory", "SayCanAgent"),
    "sciencebuddy": (
        "auto_research.agent_research.mechanisms.science_buddy_agent",
        "ScienceBuddyAgent",
    ),
    "search-r1": ("auto_research.agent_research.method_families.rl", "SearchR1Agent"),
    "searchatlas": (
        "auto_research.agent_research.mechanisms.search_atlas_agent",
        "SearchAtlasAgent",
    ),
    "searl": ("auto_research.agent_research.p0_20260808", "SEARLAgent"),
    "seed": ("auto_research.agent_research.method_families.rl", "SEEDAgent"),
    "self-refine": ("auto_research.agent_research.method_families.planning", "SelfRefineAgent"),
    "silr": ("auto_research.agent_research.mechanisms.public_observation", "SiLRAgent"),
    "sinkflex-rl": (
        "auto_research.agent_research.mechanisms.sink_window_indices",
        "SinkFlexRLAgent",
    ),
    "skill-retention": (
        "auto_research.agent_research.mechanisms.skill_retention_agent",
        "SkillRetentionAgent",
    ),
    "skillforge": ("auto_research.agent_research.mechanisms.skill_forge_agent", "SkillForgeAgent"),
    "skillrise": ("auto_research.agent_research.method_families.rl", "SkillRiseAgent"),
    "smith": ("auto_research.agent_research.mechanisms.smithagent", "SMITHAgent"),
    "spade": ("auto_research.agent_research.historical_b10_b11", "SPADEAgent"),
    "spo-plus-plus": (
        "auto_research.agent_research.mechanisms.spoplus_plus_agent",
        "SPOPlusPlusAgent",
    ),
    "spt": ("auto_research.agent_research.mechanisms.sptagent", "SPTAgent"),
    "state2state": (
        "auto_research.agent_research.mechanisms.state2_state_agent",
        "State2StateAgent",
    ),
    "steppo": ("auto_research.agent_research.method_families.rl", "StepPOAgent"),
    "swe-prime": ("auto_research.agent_research.mechanisms.sweprime_agent", "SWEPrimeAgent"),
    "t1-terminal-rl": (
        "auto_research.agent_research.mechanisms.t1_terminal_agent",
        "T1TerminalAgent",
    ),
    "tapo": ("auto_research.agent_research.method_families.rl", "TAPOAgent"),
    "toolbench": ("auto_research.agent_research.p1_20260808", "ToolBenchAgent"),
    "toolformer": ("auto_research.agent_research.method_families.planning", "ToolformerAgent"),
    "toolgrad": ("auto_research.agent_research.mechanisms.tool_grad_agent", "ToolGradAgent"),
    "toollift": ("auto_research.agent_research.historical_b10_b11", "ToolLIFTAgent"),
    "toolrl": ("auto_research.agent_research.p0_20260808", "ToolRLAgent"),
    "topas": ("auto_research.agent_research.mechanisms.topasagent", "TOPASAgent"),
    "traceml": ("auto_research.agent_research.mechanisms.trace_m_l_agent", "TraceMLAgent"),
    "trca": ("auto_research.agent_research.historical_b10_b11", "TRCAAgent"),
    "tree-of-thoughts": (
        "auto_research.agent_research.method_families.planning",
        "TreeOfThoughtsAgent",
    ),
    "turn-opd": ("auto_research.agent_research.method_families.rl", "TurnOPDAgent"),
    "u-mem": ("auto_research.agent_research.method_families.memory", "UMemAgent"),
    "unimem": ("auto_research.agent_research.method_families.rl", "UniMemAgent"),
    "vag": ("auto_research.agent_research.mechanisms.va_g_agent", "VaGAgent"),
    "vermem": ("auto_research.agent_research.method_families.rl", "VerMemAgent"),
    "voyager": ("auto_research.agent_research.method_families.planning", "VoyagerAgent"),
    "webagent-r1": ("auto_research.agent_research.method_families.rl", "WebAgentR1Agent"),
    "webgpt": ("auto_research.agent_research.method_families.memory", "WebGPTAgent"),
}

_EXPORTS = {
    "BaseAgent": ("auto_research.agent_research.method_families.base", "BaseAgent"),
    "LongContextAgent": (
        "auto_research.agent_research.method_families.planning",
        "LongContextAgent",
    ),
    "ReActAgent": ("auto_research.agent_research.method_families.planning", "ReActAgent"),
    "ReflexionAgent": ("auto_research.agent_research.method_families.planning", "ReflexionAgent"),
    "VoyagerAgent": ("auto_research.agent_research.method_families.planning", "VoyagerAgent"),
    "TreeOfThoughtsAgent": (
        "auto_research.agent_research.method_families.planning",
        "TreeOfThoughtsAgent",
    ),
    "LATSAgent": ("auto_research.agent_research.method_families.planning", "LATSAgent"),
    "ToolformerAgent": ("auto_research.agent_research.method_families.planning", "ToolformerAgent"),
    "SelfRefineAgent": ("auto_research.agent_research.method_families.planning", "SelfRefineAgent"),
    "ReWOOAgent": ("auto_research.agent_research.method_families.planning", "ReWOOAgent"),
    "AutoGenAgent": ("auto_research.agent_research.method_families.planning", "AutoGenAgent"),
    "PEARLAgent": ("auto_research.agent_research.method_families.planning", "PEARLAgent"),
    "UMemAgent": ("auto_research.agent_research.method_families.memory", "UMemAgent"),
    "LegoMemAgent": ("auto_research.agent_research.method_families.memory", "LegoMemAgent"),
    "MemToolAgent": ("auto_research.agent_research.method_families.memory", "MemToolAgent"),
    "MRKLAgent": ("auto_research.agent_research.method_families.memory", "MRKLAgent"),
    "HuggingGPTAgent": ("auto_research.agent_research.method_families.memory", "HuggingGPTAgent"),
    "GenerativeAgentsAgent": (
        "auto_research.agent_research.method_families.memory",
        "GenerativeAgentsAgent",
    ),
    "MemGPTAgent": ("auto_research.agent_research.method_families.memory", "MemGPTAgent"),
    "WebGPTAgent": ("auto_research.agent_research.method_families.memory", "WebGPTAgent"),
    "SayCanAgent": ("auto_research.agent_research.method_families.memory", "SayCanAgent"),
    "PALAgent": ("auto_research.agent_research.method_families.memory", "PALAgent"),
    "ARTAgent": ("auto_research.agent_research.method_families.memory", "ARTAgent"),
    "SEEDAgent": ("auto_research.agent_research.method_families.rl", "SEEDAgent"),
    "CASTAgent": ("auto_research.agent_research.method_families.rl", "CASTAgent"),
    "TurnOPDAgent": ("auto_research.agent_research.method_families.rl", "TurnOPDAgent"),
    "SearchR1Agent": ("auto_research.agent_research.method_families.rl", "SearchR1Agent"),
    "RAGENAgent": ("auto_research.agent_research.method_families.rl", "RAGENAgent"),
    "LOOPAgent": ("auto_research.agent_research.method_families.rl", "LOOPAgent"),
    "WebAgentR1Agent": ("auto_research.agent_research.method_families.rl", "WebAgentR1Agent"),
    "MUARLAgent": ("auto_research.agent_research.method_families.rl", "MUARLAgent"),
    "HiSkillAgent": ("auto_research.agent_research.method_families.rl", "HiSkillAgent"),
    "UniMemAgent": ("auto_research.agent_research.method_families.rl", "UniMemAgent"),
    "CAMDFAgent": ("auto_research.agent_research.method_families.rl", "CAMDFAgent"),
    "SkillRiseAgent": ("auto_research.agent_research.method_families.rl", "SkillRiseAgent"),
    "GiGPOAgent": ("auto_research.agent_research.method_families.rl", "GiGPOAgent"),
    "StepPOAgent": ("auto_research.agent_research.method_families.rl", "StepPOAgent"),
    "TAPOAgent": ("auto_research.agent_research.method_families.rl", "TAPOAgent"),
    "GRSDAgent": ("auto_research.agent_research.method_families.rl", "GRSDAgent"),
    "EnvACEAgent": ("auto_research.agent_research.method_families.rl", "EnvACEAgent"),
    "AgentOPSDAgent": ("auto_research.agent_research.method_families.rl", "AgentOPSDAgent"),
    "OCSDAgent": ("auto_research.agent_research.method_families.rl", "OCSDAgent"),
    "VerMemAgent": ("auto_research.agent_research.method_families.rl", "VerMemAgent"),
    "CoEvoMemAgent": ("auto_research.agent_research.method_families.rl", "CoEvoMemAgent"),
}
