"""Mirror the repository README into the MkDocs site with site-safe links."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "README.md"
TARGET = ROOT / "docs" / "project-readme.md"
NOTICE = "<!-- Generated by scripts/sync_project_readme.py; edit README.md instead. -->\n\n"
COUNT_PATTERN = re.compile(r"仓库目前注册 \*\*\d+ 个\*\*论文 adapter")


def normalized_source() -> str:
    content = SOURCE.read_text(encoding="utf-8")
    specifications = list(
        (ROOT / "src" / "auto_research" / "reproductions").glob("*/paper.yaml")
    )
    replacement = f"仓库目前注册 **{len(specifications)} 个**论文 adapter"
    if not COUNT_PATTERN.search(content):
        raise SystemExit("README.md is missing the generated adapter-count sentence")
    return COUNT_PATTERN.sub(replacement, content)


def rendered() -> str:
    content = normalized_source()
    # The mirrored page already lives under docs/, so repository README links
    # beginning with docs/ must become paths relative to the documentation root.
    return NOTICE + content.replace("](docs/", "](")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered()
    if args.check:
        if SOURCE.read_text(encoding="utf-8") != normalized_source():
            raise SystemExit("README.md adapter count is stale; run python scripts/sync_project_readme.py")
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("docs/project-readme.md is stale; run python scripts/sync_project_readme.py")
        return 0
    SOURCE.write_text(normalized_source(), encoding="utf-8")
    expected = rendered()
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
