"""Mirror the repository README into the MkDocs site with site-safe links."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "README.md"
TARGET = ROOT / "docs" / "project-readme.md"
NOTICE = "<!-- Generated by scripts/sync_project_readme.py; edit README.md instead. -->\n\n"


def rendered() -> str:
    content = SOURCE.read_text(encoding="utf-8")
    # The mirrored page already lives under docs/, so repository README links
    # beginning with docs/ must become paths relative to the documentation root.
    return NOTICE + content.replace("](docs/", "](")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("docs/project-readme.md is stale; run python scripts/sync_project_readme.py")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
