"""Compatibility imports; implementations live in stable mechanisms modules."""

from __future__ import annotations

from auto_research.mechanisms.llm2jev_distribution import llm2jev_distribution
from auto_research.mechanisms.llm2jev_objective import llm2jev_objective
from auto_research.mechanisms.dense_caption_distillation import dense_caption_distillation
from auto_research.mechanisms.mwop_masks import mwop_masks
from auto_research.mechanisms.af_muon_vocab_direction import af_muon_vocab_direction
from auto_research.mechanisms.rea_select_context import rea_select_context
from auto_research.mechanisms.hawk_draft_target import hawk_draft_target
from auto_research.mechanisms.ireko_nested_subnetwork import ireko_nested_subnetwork
