"""Canonical paper metadata for the 2026 historical batches B07--B11."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HistoricalPaper:
    batch: str
    domain: str
    key: str
    arxiv_id: str
    title: str
    first_author: str
    organization: str
    published: str
    topic: tuple[str, ...]
    summary: str
    formula: str
    paper_result: str
    code_url: str | None = None

    @property
    def slug(self) -> str:
        return f"{self.arxiv_id}-{self.key}"


PAPERS = (
    HistoricalPaper("B07", "foundation-models", "tcab", "2608.12831", "Fast A/B/n Testing: Exact Multi-Policy Comparison via Tree-Coupled Feedback Sharing", "Yuxiao Wen", "New York University", "2026-08-13", ("评测基础设施", "在线实验"), "用最大耦合和最小生成树共享相同决策的反馈，同时保持每个自适应策略的边际轨迹分布不变。", r"N(T)=T+\sum_{t,e}D_{e,t}", "理论上从独立 A/B/n 的 JT 次反馈降至 T+o(T)，实验改善 cost–precision frontier。"),
    HistoricalPaper("B07", "foundation-models", "olmpool-long-context", "2608.10296", "Cracks in the Foundation: Seemingly Minor Architectural Choices Impact Long Context Extension", "Amanda Bertsch", "Ai2", "2026-08-10", ("注意力与长上下文", "网络架构"), "以受控 7B 模型池隔离 normalization、GQA、预训练长度和滑窗注意力对长上下文扩展的复合影响。", r"\Delta_{LC}=f(N,G,L,S)-f(N_0,G_0,L_0,S_0)", "三个以上不利选择组合可令长上下文下游表现下降至 47%；公开 26 个 OlmPool 模型。", "https://github.com/allenai/olmpool/"),
    HistoricalPaper("B07", "foundation-models", "distillcache", "2608.08878", "DistillCache: KL-Guided Adaptive KV-Cache Eviction for Memory-Efficient LLM Inference", "Asaad Althoubi", "Oklahoma State University", "2026-08-09", ("推理与系统效率", "KV cache"), "把 KV 淘汰视为序列决策，以逐步 KL 奖励训练轻量策略保留未来预测分布。", r"r_t=-D_{KL}(p_{full,t}\Vert p_{evict,t})", "25% cache 预算保留 LongBench full-cache 94.2% 准确率，吞吐最高 2.1×。"),
    HistoricalPaper("B07", "foundation-models", "autonomy-heads", "2608.06849", "Autonomy-of-Heads: Data-Free Sparse Attention from Frozen Query-Key Geometry", "Yehan Yang", "Institute of Computing Technology, Chinese Academy of Sciences", "2026-08-07", ("注意力与长上下文", "稀疏注意力"), "直接从冻结 QK 投影的谱有效秩区分 retrieval 与 streaming heads，无需校准数据或运行时门控。", r"M_h=W_{K,h}^{\top}W_{Q,h},\quad r_{eff}(M_h)=\exp H(\sigma(M_h))", "50% 稀疏度平均保留 96.5% full-attention 表现；prefill/decode 时延最高下降 41.4%/66.0%。"),
    HistoricalPaper("B07", "foundation-models", "physics-mm-pretraining", "2608.05000", "Towards Physics of Multimodal Pretraining: Knowledge Flow, Modality Synergy, Early Unification, and Recipes", "Junlin Han", "Meta", "2026-08-05", ("多模态基础模型", "预训练与数据"), "用受控实验刻画模态知识流、协同/竞争、早期统一和共享 attention+norm/模态专属 FFN 配方。", r"\mathcal L=\mathcal L_{text}+\lambda_u\mathcal L_{understand}+\lambda_g\mathcal L_{generate}", "高效配方仅用 5% 计算预算获得强生成表现，并以 13.5B MoE、2T tokens 验证。"),
    HistoricalPaper("B07", "foundation-models", "ttcd", "2608.01672", "Learning What to Remember: Test-Time Training via Context Distillation", "Zixuan Wang", "Princeton University", "2026-08-03", ("注意力与长上下文", "测试时训练"), "长窗口教师以隐藏状态差异监督短窗口学生的 fast weights，使有限记忆优先保留未来有用信息。", r"\mathcal L_{TTCD}=\sum_t\lVert h_t^{long}-h_t^{fast}\rVert_2^2", "IP-TTCD 在长上下文语言建模中持续优于 DeltaNet、Gated DeltaNet、滑窗注意力和 TTT。", "https://github.com/dangxingyu/ttcd"),
    HistoricalPaper("B07", "foundation-models", "dart", "2608.02032", "DART: Decoded Attention over Recurrent States for Efficient Long-Context Sequence Modeling", "Yixiao Qian", "Zhejiang University", "2026-08-03", ("网络架构", "注意力与长上下文"), "保留 Mamba-2 chunk state contributions，解码 token-conditioned K/V 并执行 state-memory attention。", r"y_t=y_t^{Mamba}+g_t\operatorname{Attn}(q_t,K(S),V(S))", "chunk=256、state=128 时相对匹配 attention baseline 节省 75% 长度相关 cache。"),
    HistoricalPaper("B07", "foundation-models", "transmem", "2607.29032", "TransMem: Transforming Hidden States into Memory for Large Language Models", "Haodong Lei", "Authors did not disclose affiliation", "2026-07-31", ("注意力与长上下文", "Agent 记忆"), "将冻结骨干的稀疏历史 hidden states 变换成可复用参数记忆，并用 evidence-conditioned self-distillation 学门控。", r"h'_t=h_t+g_t\odot T(H_{sparse})", "LoCoMo +11.58–29.25 F1，HotpotQA +10.20–13.03 F1，MemoryAgentBench 29.54%→40.00%。"),
    HistoricalPaper("B07", "foundation-models", "c2kv", "2607.17715", "C²KV: Compressed and Composable KV Cache Reuse for Efficient LLM Inference", "Chuheng Du", "Shanghai Jiao Tong University", "2026-07-20", ("推理与系统效率", "KV cache"), "以 compression tokens 和结构化 attention 学习位置无关、可拼接的压缩 KV manifold，并联合训练压缩与复用。", r"Z=\operatorname{Extractor}(KV),\quad \hat y=F([Z_1;\ldots;Z_m])", "跨长上下文 benchmark 最高 17× 推理加速并保持生成质量。", "https://github.com/s7a9/C2KV"),
    HistoricalPaper("B08", "post-training", "r2-opd", "2608.19408", "Beyond Imitation: Filtering On-Policy Distillation by Reasoning Progress", "Chen Yang", "Authors did not disclose affiliation", "2026-08-19", ("OPD", "过程蒸馏"), "分别按教师奖励和独立进展奖励排序 reasoning spans，冲突时屏蔽蒸馏信号。", r"A_i^{R^2}=A_i^{OPD}\mathbf1[\operatorname{rank}(r_i^T)=\operatorname{rank}(r_i^P)]", "论文报告在多个 reasoning benchmark 上稳定优于标准 OPD，困难任务收益更明显。"),
    HistoricalPaper("B08", "post-training", "sr-opsd", "2608.09745", "SR-OPSD: Self-Referenced On-Policy Self-Distillation", "Zhuo Sun", "Independent Researcher", "2026-08-10", ("OPD", "自蒸馏"), "把自教师与 reference 做几何插值得到有效目标，再用 Rényi divergence 控制投影几何和密度比敏感度。", r"q_\beta(y)\propto p_T(y)^\beta p_{ref}(y)^{1-\beta}", "科学、数学和代码任务的多模型实验达到 SOTA 或具有竞争力的结果。"),
    HistoricalPaper("B08", "post-training", "opd2", "2608.05802", "On-Policy Delta Distillation for Multilingual Math Reasoning", "Byeongho Heo", "NAVER AI Lab", "2026-08-06", ("OPD", "多语言推理"), "以 post-trained teacher 相对其 base model 的概率增量作为蒸馏信号，减少复制教师原有偏差。", r"\Delta_T=\log p_{T^+}-\log p_{T^0}", "Qwen3 上持续优于原始 OPD，韩语和日语提升尤为明显。", "https://github.com/naver-ai/opd2"),
    HistoricalPaper("B08", "post-training", "causal-opd", "2608.03673", "CausalOPD: First-Wrong-Step Supervision for Distilling Causal Chain Reasoning", "Jian Zhang", "Authors did not disclose affiliation", "2026-08-04", ("OPD", "过程监督"), "教师定位 on-policy 因果链第一个错误步骤，以短 horizon RL 修复，并按证据→机制→结论推进课程。", r"t^*=\min\{t:C(s_t,a_t)=0\}", "三领域平均 path correctness 相对 sequence OPD +23.4 points，RLWR 15.7%→4.4%。"),
    HistoricalPaper("B08", "post-training", "smopd", "2608.03092", "SMOPD: Multi-Reward Reinforcement Learning via Specialize-and-Merge Online Policy Distillation", "Wen Wang", "Alibaba / Qwen", "2026-08-04", ("OPD", "多奖励 RL"), "先用 reward-priority 分别训练专长教师，再在学生自身轨迹上合并多个教师能力。", r"\mathcal L=\sum_k\alpha_kD_{KL}(p_{T_k}\Vert p_\theta)", "在互补和冲突多奖励设置、1.5B/3B/7B backbone 上均优于 GDPO。"),
    HistoricalPaper("B08", "post-training", "rstg", "2608.00782", "Distill Where You Fail: Recovering Learning Signals of Negative RL-Groups from Adaptive Teacher Guidance", "Zhuowen Han", "Tianjin University", "2026-08-01", ("OPD", "RLVR"), "只对负向零方差 group 启用教师，并在高熵或大 teacher-student gap token 上蒸馏，同时注入教师正确轨迹 SFT。", r"\mathcal L=\mathcal L_{GRPO}+\mathbf1[\operatorname{Var}(R)=0,R=0]\mathcal L_{OPD}", "相对 naive GRPO+OPD，数学 +4.02%，代码 +3.05%。"),
    HistoricalPaper("B09", "post-training", "sa-mrpo", "2608.16072", "Learn What's Left, Not What's Mastered: Saturation Aware Advantage Reweighting for Multi-Reward Policy Optimization", "Yixuan Wang", "University of Florida", "2026-08-17", ("多奖励 RL", "稳定性"), "逐 reward 维度标准化优势，并依据 batch 饱和度动态把梯度预算转移到尚未掌握的目标。", r"A=\sum_k(1-s_k)\frac{r_k-\mu_k}{\sigma_k+\epsilon}", "困难正确率在 15 项比较中赢 12 项；AIME24 最高 +5%，AMC23 +9.2%。"),
    HistoricalPaper("B09", "post-training", "rubric-dropout", "2608.11669", "Rubric Dropout: A Simple Way to Mitigate Reward Hacking in Rubric-as-Reward RL", "Minglai Yang", "Scale AI", "2026-08-12", ("Rubric RL", "reward hacking"), "每个 rollout group 共享随机丢弃的 rubric 子集，使策略无法持续利用固定 judge proxy。", r"R_{drop}(y)=\sum_k m_kr_k(y),\quad m_k\sim Bernoulli(1-p)", "30–50% dropout 在 OOD gold judge 上提升 HealthBench-Hard 1–2 points、ResearchQA 6–7 points。"),
    HistoricalPaper("B09", "post-training", "erils", "2608.01717", "Beyond On-Policy Exploration: Integrating External Policy Rollouts for Reinforcement Learning in Diffusion Language Models", "Wonseok Lee", "Seoul National University", "2026-08-03", ("外部 rollout", "Diffusion LM RL"), "约束外部策略 rollout 长度，并对 on-policy/external 来源分别处理奖励以防联合归一化崩溃。", r"A_i=\operatorname{Norm}_{source(i)}(R_i),\quad |y_i|\le L", "Sudoku best-of-4 98.4%，强基线 40.3%；不同生成长度 deterministic accuracy 约 90%。"),
    HistoricalPaper("B09", "post-training", "crpo", "2607.28026", "Contrastive Reinforced Policy Optimization via Privileged Self-Distillation", "Xingjian Wu", "Authors did not disclose affiliation", "2026-07-30", ("OPD", "Agentic RL"), "按预测熵区分反思探索正位置和 exposure-bias 负位置，对 privileged self-distillation 做组内对比。", r"\mathcal L_{CRPO}=-\log\frac{e^{s^+/\tau}}{e^{s^+/\tau}+\sum_j e^{s_j^-/\tau}}", "13 个 reasoning/deep-search benchmark 上持续优于 RL 与自蒸馏基线。"),
    HistoricalPaper("B09", "post-training", "serpo", "2607.26873", "SERPO: Self-Evolving Rubric Policy Optimization for Open-Ended Test-Time Reinforcement Learning", "Jianze Wang", "Authors did not disclose affiliation", "2026-07-29", ("Rubric RL", "测试时自进化"), "让 Good–Normal–Bad 响应档案、query-specific rubrics 和 actor 策略形成三方闭环自进化。", r"\theta,rubric,archive\leftarrow\operatorname{Evolve}(\theta,rubric,archive)", "HealthBench/ResearchQA 最高 +20.63/+20.31 points，六 benchmark macro +8.06。"),
    HistoricalPaper("B09", "post-training", "iso-rlvr", "2607.19331", "ISO: An RLVR-Native Optimization Stack", "Hanqing Zhu", "The University of Texas at Austin", "2026-07-21", ("RLVR", "优化器"), "固定预训练权重奇异值，仅优化输入/输出 singular frames；同时提供无数据 specialist merger。", r"W=U\Sigma_0V^\top,\quad \Sigma_0\ \text{fixed}", "Qwen3-8B aggregate 0.495：AdamW 270 steps，ISO-AdamW 100 steps；210 steps 达 0.509。", "https://github.com/zhuhanqing/ISO"),
    HistoricalPaper("B10", "agent-research", "sapo", "2608.19842", "SAPO: Single-Rollout Autoregressive Policy Optimization for Agentic Reinforcement Learning", "Dayang Liang", "Xiamen University", "2026-08-20", ("Agentic RL", "credit assignment"), "同一自回归骨干在不同因果边界输出 policy/value，结合 PPO、on-policy SARSA 和 trajectory GAE。", r"\hat A_t^{GAE}=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}", "ALFWorld/WebShop 平均超过 PPO 15.1 points、GRPO 12.1 points；迭代时间较 PPO -33.2%。"),
    HistoricalPaper("B10", "agent-research", "spade", "2608.19197", "SPADE: Self-Play in Adaptive Synthetic Executable Environments", "Bo Liu", "University of Washington", "2026-08-19", ("Agentic RL", "环境生成"), "同一 LLM 分饰环境设计者和推理 Agent，以有/无 privileged hint 的 regret 学习能力边界上的可执行环境。", r"R_{designer}=R_{hint}-R_{agent}", "30B 规模跨八项 held-out 平均 +5.3；BFCL v4 +5.7、ACEBench-Agent +13.9。", "https://github.com/spade-rl/spade"),
    HistoricalPaper("B10", "agent-research", "rtpo", "2608.18682", "RTPO: Reverse-Turn Policy Optimization for Stabilizing Agentic RL Training", "Yugu Li", "Adelaide University", "2026-08-19", ("Agentic RL", "credit assignment"), "把多轮 rollout 组织成稀疏反向树，按时间逆序更新 turn，令决策与下游 continuation 保持 on-policy。", r"\pi_{t}\leftarrow\arg\max_\pi\mathbb E[A_t^{reverse}\log\pi(a_t|s_t)]", "相对 trajectory-level 与 turn-level 基线分别提升 21.50% 和 10.76%。"),
    HistoricalPaper("B10", "agent-research", "planpo", "2608.17289", "PlanPO: Group Planning-Aware Policy Optimization for Multi-Turn Agentic LLMs", "Dayang Liang", "Xiamen University", "2026-08-18", ("Agentic RL", "规划"), "在成功轨迹内同时比较 trajectory turn 数和单 turn response 长度，形成 coarse-to-fine planning advantages。", r"A=A_{outcome}+\alpha A_{turn-count}+\beta A_{response-length}", "ALFWorld、WebShop、SciWorld 平均相对 GRPO +27.2%，额外开销可忽略。"),
    HistoricalPaper("B10", "agent-research", "trca", "2608.16156", "TRCA: Transition-wise Rubric Credit Assignment for Long-horizon LLM Agents", "Huan Zhang", "Authors did not disclose affiliation", "2026-08-17", ("Agentic RL", "过程奖励"), "无需成功 anchor，从每个状态转移的 Evidence、Execution、Invalidity rubric 构造基础和 breakthrough reward。", r"r_t=r_t^{evidence}+r_t^{execution}-r_t^{invalid}+r_t^{breakthrough}", "WebShop 相对基线 +6.0%–12.6%；SearchQA 平均 +1.9%–18.3%。"),
    HistoricalPaper("B10", "agent-research", "loongreflect", "2608.11967", "LoongReflect: Boosting Long-Horizon Reflection in Search Agents via Global Perspective Distillation", "Zhixin Zhang", "Authors did not disclose affiliation", "2026-08-12", ("反思", "Agentic RL"), "把 reflect/backtrack 视为可逆轨迹树的 memory-control actions，以 privileged teacher 快通道和 outcome GRPO 慢通道协调训练。", r"\mathcal L=\mathcal L_{reflect\text{-}OPD}+\lambda\mathcal L_{trajectory\text{-}GRPO}", "多跳 RAG 和数学推理中持续优于 outcome-only RL 与 self-distillation。"),
    HistoricalPaper("B11", "agent-research", "hymem", "2608.15703", "HyMem: Hierarchical Context Management for Long-Horizon Agents via Information Isolation", "XinQi Wang", "Institute of Automation, Chinese Academy of Sciences", "2026-08-16", ("记忆", "长时序 Agent"), "把 planning、execution 和 isolated reasoning 分层，结构化摘要在 context refresh 间保存任务进展。", r"C_t=C_t^{plan}\oplus C_t^{exec}\oplus M_t^{summary}", "DeepSeek-V4 在 GAIA/BrowseComp-plus Pass@1 达 66.7%/61.3%。"),
    HistoricalPaper("B11", "agent-research", "openloopevolve", "2608.09380", "OpenLoopEvolve: A Verifiable Self-Evolution Framework for Loop Policies in Long-Horizon Complex Tasks", "Siqi Wang", "Tsinghua University", "2026-08-10", ("自进化", "策略治理"), "把 observation/planning/memory/action/verification/recovery 等 Loop Policy 资产版本化，以 Champion–Challenger、发布监控和回滚治理进化。", r"\pi_{v+1}=\operatorname{Release}(\arg\max_{c\in C}Eval(c,\pi_v))", "YC-Bench 在线和离线进化均改善聚合表现、成功率与风险指标。", "https://github.com/yoyoshikc/OpenLoopEvolve"),
    HistoricalPaper("B11", "agent-research", "pmcoder", "2608.06811", "Coupling Planning with Episodic Memory in LLM Agents for Software Issue Resolution", "Jiahao Zhang", "Vanderbilt University", "2026-08-07", ("代码 Agent", "记忆与规划"), "用层级 phase planner 条件化 episodic retrieval，再用记忆轨迹统计检测 stuck 并重规划，以真实执行 verdict 验证。", r"m_t=Retrieve(M,phase_t),\quad phase_{t+1}=Replan(s_t,m_t)", "SWE-bench Verified 比 harness-matched baseline 多解决 25 个（+5.0 pp）；跨模型至少 +14 个。"),
    HistoricalPaper("B11", "agent-research", "toollift", "2608.03468", "ToolLIFT: Lifting Tool-Specific Trajectories into Function-Level Graphs for Generalizable Tool Planning", "Xiuhui You", "Authors did not disclose affiliation", "2026-08-04", ("工具规划", "图结构"), "把工具级历史轨迹提升为可跨工具集迁移的 function workflow graph，再解耦 workflow planning 与 tool selection。", r"G_F=Lift(\tau_{tool}),\quad tool_t=Select(f_t,s_t)", "两项 ID 和三项 OOD benchmark 均优于所比较 SOTA，尤其提升未见工具集泛化。"),
    HistoricalPaper("B11", "agent-research", "hyperagent", "2608.02650", "HyperAgent: Planning and Acting over Tool-Schema Hypergraphs for Tool-Use LLM Agents", "Zian Zhai", "University of New South Wales", "2026-07-31", ("工具规划", "超图"), "把工具建模为 input-schema→output-schema 超边，先构造 Task DAG，再按状态缺口扩展 producer tool support graph。", r"e_{tool}:\{schema_{in}\}\rightarrow\{schema_{out}\}", "AppWorld 上提高任务完成率，同时减少冗余 API、LLM 交互和 token 消耗。"),
    HistoricalPaper("B11", "agent-research", "manta", "2607.28527", "MANTA: Multi-Agent Network Topology Adaptation for Self-Evolving Multi-Agent Systems", "MaoXun Huang", "Cornell University", "2026-07-30", ("多 Agent", "自进化"), "根据任务先验初始化通信拓扑，运行中监控协作 trace，并有界调整角色、边、顺序、可见性和验证路径。", r"G_{t+1}=\Pi_{budget}(G_t+\Delta G(\tau_t))", "五项 benchmark 平均 74.0，超过最强基线 5.8 points，并在 PlanCraft 最优。"),
)


BY_KEY = {paper.key: paper for paper in PAPERS}
BY_ID = {paper.arxiv_id: paper for paper in PAPERS}
