"""Seven full-text-reviewed omissions from the October 2 announcement."""


def _paper(key, title, aid, domain, topic, author, institution, date, priority, code=None):
    return dict(
        key=key,
        title=title,
        paper_url=f"https://arxiv.org/abs/{aid}",
        domain=domain,
        detail_path=f"{domain}/{aid}-{key}/README.md",
        topic=topic,
        first_author=author,
        first_author_affiliation=institution,
        published=date,
        priority=priority,
        code=code,
        adapter=key,
    )


LATEST_METHOD_PAPERS = (
    _paper(
        "jev-lookahead",
        "Code Owns the Simulation, Jev Owns the Evaluation",
        "2610.01834",
        "agent-research",
        ["模拟前瞻与动作选择", "System One"],
        "Yaodong Yang",
        "The Chinese University of Hong Kong",
        "2026-10-01",
        "P0",
    ),
    _paper(
        "t2spo",
        "T2SPO: Trajectory-to-Step Policy Optimization for Agentic Reinforcement Learning",
        "2610.00388",
        "post-training",
        ["轨迹到步骤信用分配", "强化学习"],
        "Bo-Wen Zhang",
        "Nanjing University",
        "2026-09-30",
        "P0",
    ),
    _paper(
        "weakest-link",
        "The Weakest Link: Distilling LLM Reasoning with Worst-Case Constrained Reinforcement Learning",
        "2610.00332",
        "post-training",
        ["教师前缀约束蒸馏", "约束强化学习"],
        "Matthieu Zimmer",
        "Huawei Noah’s Ark Lab",
        "2026-09-29",
        "P0",
    ),
    _paper(
        "causal-memory-policy",
        "Causal Memory Policy: Making Memory Utility Identifiable by Intervening on Retrieval",
        "2610.02070",
        "agent-research",
        ["因果检索干预", "记忆管理"],
        "Arman Behnam",
        "Illinois Institute of Technology",
        "2026-10-01",
        "P1",
        "https://anonymous.4open.science/r/cmp-release-D0C3/",
    ),
    _paper(
        "tess",
        "TESS: Scalable, Transferable Meta-network for Data Selection Requires a Different Loss (and Why the Obvious Choice is Problematic)",
        "2610.02092",
        "foundation-models",
        ["预训练与数据", "元网络数据选择"],
        "Zilin Du",
        "Nanyang Technological University",
        "2026-10-01",
        "P1",
    ),
    _paper(
        "rlcpr",
        "RLCPR: Rethinking Probability-Based Reinforcement Learning From Posterior Concentration",
        "2610.01458",
        "post-training",
        ["后验集中与长度约束", "强化学习"],
        "Shiu-Hong Kao",
        "National University of Singapore",
        "2026-10-01",
        "P1",
    ),
    _paper(
        "mingbird",
        "Mingbird: A Local-First Agent Harness Enabling Small Open Models to Complete Real Tasks",
        "2610.02001",
        "agent-research",
        ["本地 Agent 运行框架", "工具使用"],
        "Hao Wang",
        "University of Science and Technology Beijing",
        "2026-10-01",
        "P1",
        "https://github.com/Mingbird/Mingbird-agent",
    ),
)
