"""Reviewed P0/P1 metadata for the 2026-09-19 window."""

ANGLE_PAPER = {"domain":"recommendation","key":"angle","title":"One-Step Retrieval Framework for Real-Time Sponsored Search Ads Using Hierarchical Text Representations","paper_url":"https://arxiv.org/abs/2609.18296","detail_path":"reproductions/2609.18296-angle/README.md","topic":["广告检索","生成式召回","层次标识"],"first_author":"Jinrui Zhang","first_author_affiliation":"Tencent","published":"2026-09-16","code":None,"adapter":"angle","priority":"P0"}

LATEST_METHOD_PAPERS = (
    {"domain":"post-training","key":"retire-opd","title":"RetireOPD: Self-Retiring On-Policy Distillation for Agentic Reinforcement Learning","paper_url":"https://arxiv.org/abs/2609.20784","detail_path":"post-training/2609.20784-retire-opd/README.md","topic":["On-policy distillation","Agent RL"],"first_author":"ZJU-REAL team","first_author_affiliation":"Zhejiang University","published":"2026-09-17","code":"https://github.com/ZJU-REAL/SDAR","adapter":"retire-opd","priority":"P0"},
    {"domain":"foundation-models","key":"oda","title":"On-Demand Attention: Efficient Long-Context Decoding with Learned Recall","paper_url":"https://arxiv.org/abs/2609.20734","detail_path":"foundation-models/2609.20734-oda/README.md","topic":["注意力与长上下文","推理效率"],"first_author":"Paper author team","first_author_affiliation":"Southern University of Science and Technology","published":"2026-09-17","code":None,"adapter":"oda","priority":"P0","requires_gpu_validation":True,"gpu_validation_artifact":"docs/gpu-validations/oda-a100-20260919.json"},
    {"domain":"agent-research","key":"evoskill-gui","title":"Reflect, Revise, Reuse: Training-Free Skill Evolution for GUI Agents","paper_url":"https://arxiv.org/abs/2609.17653","detail_path":"agent-research/2609.17653-evoskill-gui/README.md","topic":["GUI Agent","技能进化"],"first_author":"Bofan Chen","first_author_affiliation":"Zhejiang University","published":"2026-09-15","code":"https://github.com/ZJU-REAL/EvoSkill-GUI","adapter":"evoskill-gui","priority":"P0"},
    {"domain":"post-training","key":"compo","title":"A Zeroth-Order Paradigm for LLM Preference Alignment","paper_url":"https://arxiv.org/abs/2609.19144","detail_path":"post-training/2609.19144-compo/README.md","topic":["偏好优化","零阶优化"],"first_author":"Peter Chen","first_author_affiliation":"University of California, Berkeley","published":"2026-09-16","code":None,"adapter":"compo","priority":"P1"},
    {"domain":"post-training","key":"trajectory-learnability","title":"Trajectory Learnability for Offline On-Policy Distillation","paper_url":"https://arxiv.org/abs/2609.18321","detail_path":"post-training/2609.18321-trajectory-learnability/README.md","topic":["On-policy distillation","轨迹加权"],"first_author":"Yihao Ai","first_author_affiliation":"National University of Singapore","published":"2026-09-16","code":None,"adapter":"trajectory-learnability","priority":"P1"},
    {"domain":"agent-research","key":"dependency-refinement","title":"Dependency-Aware Trajectory Refinement for Efficient Multi-Turn Agent Fine-Tuning","paper_url":"https://arxiv.org/abs/2609.18417","detail_path":"agent-research/2609.18417-dependency-refinement/README.md","topic":["轨迹精炼","Agent 微调"],"first_author":"Zhuo Chen","first_author_affiliation":"ShanghaiTech University","published":"2026-09-16","code":"https://github.com/Alibaba-NLP/VLLM-KB","adapter":"dependency-refinement","priority":"P1"},
    {"domain":"agent-research","key":"harness-design-study","title":"An Empirical Study of Harness Design for Coding Agents","paper_url":"https://arxiv.org/abs/2609.20804","detail_path":"agent-research/2609.20804-harness-design-study/README.md","topic":["编程 Agent","Harness 设计"],"first_author":"Run-Ze Fan","first_author_affiliation":"University of Massachusetts Amherst","published":"2026-09-17","code":None,"adapter":"harness-design-study","priority":"P1"},
    {"domain":"agent-research","key":"cera-moa","title":"CERA-MoA: Co-Evolving Router and Agents for Mixture-of-Agents","paper_url":"https://arxiv.org/abs/2609.18779","detail_path":"agent-research/2609.18779-cera-moa/README.md","topic":["多 Agent","路由与协同进化"],"first_author":"Jiaxuan Jiang","first_author_affiliation":"IIIS, Tsinghua University","published":"2026-09-16","code":None,"adapter":"cera-moa","priority":"P1"},
    {"domain":"foundation-models","key":"dqwen35","title":"dQwen3.5: Adapting Hybrid Language Models into Bidirectional Diffusion Language Models","paper_url":"https://arxiv.org/abs/2609.20751","detail_path":"foundation-models/2609.20751-dqwen35/README.md","topic":["扩散语言模型","网络架构"],"first_author":"Anton Xue","first_author_affiliation":"University of Texas at Austin","published":"2026-09-17","code":None,"checkpoint":"https://huggingface.co/UT-IFML/dQwen3.5-9B-Base","adapter":"dqwen35","priority":"P1","requires_gpu_validation":True,"gpu_validation_artifact":"docs/gpu-validations/dqwen35-a100-20260919.json"},
    {"domain":"foundation-models","key":"aspire","title":"ASPIRE: Asynchronous Batch Self-Speculative Decoding","paper_url":"https://arxiv.org/abs/2609.17943","detail_path":"foundation-models/2609.17943-aspire/README.md","topic":["推测解码","推理效率"],"first_author":"Amir Ziashahabi","first_author_affiliation":"University of Southern California","published":"2026-09-16","code":None,"adapter":"aspire","priority":"P1","requires_gpu_validation":True,"gpu_validation_artifact":"docs/gpu-validations/aspire-a100-20260919.json"},
)
