"""Reviewed papers in the October 5 arXiv announcement; partial source coverage."""


LATEST_METHOD_PAPERS = (
    {
        "domain": "agent-research",
        "key": "adastep",
        "title": "AdaStep: Adaptive Step Credit Weighting for Agentic Reinforcement Learning",
        "paper_url": "https://arxiv.org/abs/2610.03223",
        "detail_path": "agent-research/2610.03223-adastep/README.md",
        "topic": ["Agentic RL", "步骤信用分配", "方差可靠性"],
        "first_author": "Xin Wang",
        "first_author_affiliation": "Tsinghua University",
        "published": "2026-10-02",
        "priority": "P1",
        "code": None,
        "adapter": "adastep",
    },
    {
        "domain": "post-training",
        "key": "follow-the-winners",
        "title": "Follow the Winners: Conservative Policy Improvement with the Cross-Entropy Method for Critic-Free RFT",
        "paper_url": "https://arxiv.org/abs/2610.03361",
        "detail_path": "post-training/2610.03361-follow-the-winners/README.md",
        "topic": ["Agentic RL", "无 critic 策略改进", "精英轨迹筛选"],
        "first_author": "Joery A. de Vries",
        "first_author_affiliation": "Trent AI Limited",
        "published": "2026-10-02",
        "priority": "P1",
        "code": None,
        "adapter": "follow-the-winners",
    },
    {
        "domain": "post-training",
        "key": "lesser",
        "title": "LESSER: Post-Training Data Selection with Output-Layer Gradients",
        "paper_url": "https://arxiv.org/abs/2610.03702",
        "detail_path": "post-training/2610.03702-lesser/README.md",
        "topic": ["后训练数据选择", "梯度特征", "计算效率"],
        "first_author": "Lyuxin David Zhang",
        "first_author_affiliation": "University of Pennsylvania",
        "published": "2026-10-02",
        "priority": "P1",
        "code": None,
        "adapter": "lesser",
    },
)
