"""Deprecated intake-batch view; edit paper_specs/catalog instead."""

from .paper_specs.catalog import legacy_records

LATEST_METHOD_PAPERS = legacy_records(
    (
        (
            ("agent-research", "meta-reasoning"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "context-lm"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "meta-skills"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "branch-mixture"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "advisd"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "gats"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("recommendation", "cohortmix-ts"),
            {
                "title": "Challenges and Solutions for Bandits in the Wild: Warm-Started Mixture Bandits for Cross-Cohort Slate Recommendation",
                "paper_url": "https://arxiv.org/abs/2609.37800",
                "topic": ["冷启动", "Slate bandit", "跨 cohort 迁移"],
                "first_author": "Serafima Lebedeva",
                "published": "2026-09-29",
                "code": "https://github.com/etowho/university-games",
                "adapter": "cohortmix-ts",
                "priority": "P0",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("recommendation", "recap-ctr"),
            {
                "title": "Beyond Interaction Capacity: Estimator Scaling with Recursive Models for CTR Prediction",
                "paper_url": "https://arxiv.org/abs/2609.37905",
                "topic": ["CTR", "Estimator scaling", "递归网络"],
                "first_author": "Shivang Chopra",
                "published": "2026-09-29",
                "adapter": "recap-ctr",
                "priority": "P1",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "maestro-opd"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "ipd"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "flowmap-opd"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "vjepa-policy"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "ce-guided-moe"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "tadm"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "pumba"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "splash"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
    )
)
