"""Deprecated intake-batch view; edit paper_specs/catalog instead."""

from .paper_specs.catalog import legacy_records

LATEST_METHOD_PAPERS = legacy_records(
    (
        (
            ("recommendation", "evoskillrec"),
            {
                "title": "EvoSkillRec: Skill-Genome Evolution for Recommender Architecture Discovery",
                "paper_url": "https://arxiv.org/abs/2609.34552",
                "topic": ["推荐模型自动进化", "结构搜索"],
                "published": "2026-09-28",
                "code": "https://github.com/Xiaopengli1/EvoSkill-Rec",
                "adapter": "evoskillrec",
                "priority": "P1",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("recommendation", "promptshift"),
            {
                "title": "Measuring and Mitigating Identity-Cue Preference Drift in LLM-based Recommender Systems",
                "paper_url": "https://arxiv.org/abs/2609.34229",
                "topic": ["LLM 推荐", "公平性与漂移"],
                "published": "2026-09-28",
                "adapter": "promptshift",
                "priority": "P1",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "telescopic-lm"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("foundation-models", "frac-ssm"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "rfpo"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "olive"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "ross"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "r2-opd"),
            {
                "title": "Reward-Aligned Reweighting for On-Policy Distillation",
                "paper_url": "https://arxiv.org/abs/2609.35517",
                "detail_path": "post-training/2609.35517-r2-opd/README.md",
                "topic": ["On-policy distillation", "奖励对齐重加权"],
                "first_author": "Haofeng Xu",
                "first_author_affiliation": "The University of Hong Kong",
                "published": "2026-09-28",
                "priority": "P1",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "mas-opd"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "dr-credit"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "ccm"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "sage-planner"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "certified-selective-eval"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "mnemon"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
    )
)
