"""Reviewed P0/P1 method metadata for the 2026-09-16 follow-up window."""

LATEST_METHOD_PAPERS = (
    {"domain":"foundation-models","key":"echo","title":"ECHO: Early-layer Collaborative Hierarchical Orchestration with Bonus Logits in Speculative Decoding","paper_url":"https://arxiv.org/abs/2609.17241","detail_path":"foundation-models/2609.17241-echo/README.md","topic":["推测解码","推理效率"],"first_author":"Ziyang Ma","first_author_affiliation":"Wuhan University","published":"2026-09-15","code":"https://github.com/whucs21Mzy/ECHO","adapter":"echo","priority":"P0","requires_gpu_validation":True,"gpu_validation_artifact":"docs/gpu-validations/echo-a100-20260916.json"},
    {"domain":"multimodal-models","key":"videomm","title":"VideoMM: Adaptive Macro-Micro Inference for Efficient Video MLLMs","paper_url":"https://arxiv.org/abs/2609.16722","detail_path":"multimodal-models/2609.16722-videomm/README.md","topic":["视频理解","Token 压缩"],"first_author":"Haoyu Guo","first_author_affiliation":"University of Science and Technology of China","published":"2026-09-15","code":"https://github.com/adfh917k/VideoMM","adapter":"videomm","priority":"P0","requires_gpu_validation":True,"gpu_validation_artifact":"docs/gpu-validations/videomm-a100-20260916.json"},
    {"domain":"post-training","key":"tiao","title":"TIAO: Token Importance-Aware Policy Optimization for Text Summarization","paper_url":"https://arxiv.org/abs/2609.16748","detail_path":"post-training/2609.16748-tiao/README.md","topic":["强化学习","Token 信用分配"],"first_author":"Qixiu Li","first_author_affiliation":"National University of Defense Technology","published":"2026-09-15","code":"https://github.com/TechCloud-x/TIAO","adapter":"tiao","priority":"P0","requires_gpu_validation":True,"gpu_validation_artifact":"docs/gpu-validations/tiao-a100-20260916.json"},
    {"domain":"agent-research","key":"repoatlas","title":"RepoAtlas: Guiding Coding Agents via Evolving Multimodal Repository Views","paper_url":"https://arxiv.org/abs/2609.16936","detail_path":"agent-research/2609.16936-repoatlas/README.md","topic":["编程 Agent","多模态仓库视图"],"first_author":"Yunxiang Zhang","first_author_affiliation":"Beihang University","published":"2026-09-15","code":None,"adapter":"repoatlas","priority":"P0"},
    {"domain":"multimodal-models","key":"stacktok","title":"StackTok: Accelerating VLMs Inference with Budget-Adaptive Visual Token Selection","paper_url":"https://arxiv.org/abs/2609.16841","detail_path":"multimodal-models/2609.16841-stacktok/README.md","topic":["视觉 Token 选择","推理效率"],"first_author":"Zhenbin Wang","first_author_affiliation":"Sichuan University","published":"2026-09-15","code":"https://github.com/wongzbb/StackToK","adapter":"stacktok","priority":"P1"},
    {"domain":"agent-research","key":"interactive-memory","title":"Interactive Memory Learning for Long-Term Conversations","paper_url":"https://arxiv.org/abs/2609.17088","detail_path":"agent-research/2609.17088-interactive-memory/README.md","topic":["长期记忆","多 Agent 强化学习"],"first_author":"Cai Ke","first_author_affiliation":"Harbin Institute of Technology, Shenzhen / Pengcheng Laboratory","published":"2026-09-15","code":None,"adapter":"interactive-memory","priority":"P1"},
    {"domain":"post-training","key":"sd-dpo","title":"Style-Debiased DPO: Updating LLM Knowledge with Factuality-Aware Synthetic Preference Data","paper_url":"https://arxiv.org/abs/2609.16532","detail_path":"post-training/2609.16532-sd-dpo/README.md","topic":["偏好优化","知识更新"],"first_author":"Takayuki Yamamoto","first_author_affiliation":"Waseda University","published":"2026-09-15","code":None,"adapter":"sd-dpo","priority":"P1"},
    {"domain":"foundation-models","key":"open-1b-audit","title":"OPEN-1B: A Fully Auditable Training Run","paper_url":"https://arxiv.org/abs/2609.17380","detail_path":"foundation-models/2609.17380-open-1b-audit/README.md","topic":["可复现训练","训练审计"],"first_author":"John Donaghy","first_author_affiliation":"Gensyn","published":"2026-09-15","code":"https://github.com/gensyn-ai/open-transformers","code_extra":"https://github.com/gensyn-ai/pretraining-audit-cli","adapter":"open-1b-audit","priority":"P1"},
    {"domain":"foundation-models","key":"persistent-recurrent-memory","title":"Persistent Recurrent Memory Between Transformer Layers Improves Language Model Generalization","paper_url":"https://arxiv.org/abs/2609.17251","detail_path":"foundation-models/2609.17251-persistent-recurrent-memory/README.md","topic":["网络架构","持久记忆"],"first_author":"Eduardo Novaes Hering","first_author_affiliation":"FITec Labs / Ericsson São Paulo","published":"2026-09-15","code":None,"adapter":"persistent-recurrent-memory","priority":"P1"},
    {"domain":"foundation-models","key":"register-tokens-dllm","title":"Register Tokens for Bounded-State Reasoning in Diffusion Language Models","paper_url":"https://arxiv.org/abs/2609.16372","detail_path":"foundation-models/2609.16372-register-tokens-dllm/README.md","topic":["扩散语言模型","长程推理"],"first_author":"Albert Ge","first_author_affiliation":"University of Wisconsin–Madison","published":"2026-09-14","code":None,"adapter":"register-tokens-dllm","priority":"P1"},
)

