"""Reviewed P0/P1 method metadata through 2026-09-16."""

LATEST_METHOD_PAPERS = (
    {"domain":"post-training","key":"gamma-opd","title":"Beyond Token-Local Imitation: Reward-Compatible Temporal Credit Assignment for On-Policy Distillation","paper_url":"https://arxiv.org/abs/2609.16937","detail_path":"post-training/2609.16937-gamma-opd/README.md","topic":["On-policy distillation","时间信用分配"],"first_author":"Shiqi Liu","first_author_affiliation":"Tsinghua University / DiDi Voyager Labs","published":"2026-09-15","code":None,"adapter":"gamma-opd","priority":"P0"},
    {"domain":"post-training","key":"tlm-dre","title":"Turn-level Multiscale Density Ratio Estimation for LLM Agents","paper_url":"https://arxiv.org/abs/2609.16760","detail_path":"post-training/2609.16760-tlm-dre/README.md","topic":["多轮 Agent 对齐","密度比估计"],"first_author":"Zishuo Zhao","first_author_affiliation":"Alibaba Group","published":"2026-09-15","code":None,"adapter":"tlm-dre","priority":"P0"},
    {"domain":"post-training","key":"stride-opd","title":"Know When to Stop, Where to Restart: Accelerating Multi-Turn Agentic On-Policy Distillation","paper_url":"https://arxiv.org/abs/2609.14636","detail_path":"post-training/2609.14636-stride-opd/README.md","topic":["On-policy distillation","多轮加速"],"first_author":"Zhiyu Gui","first_author_affiliation":"University of Science and Technology of China / Ant Group","published":"2026-09-13","code":None,"adapter":"stride-opd","priority":"P0"},
    {"domain":"post-training","key":"df-opd","title":"Data-free On-policy Distillation","paper_url":"https://arxiv.org/abs/2609.14193","detail_path":"post-training/2609.14193-df-opd/README.md","topic":["On-policy distillation","数据合成"],"first_author":"Gengsheng Li","first_author_affiliation":"Institute of Automation, Chinese Academy of Sciences / Tencent","published":"2026-09-12","code":None,"adapter":"df-opd","priority":"P0"},
    {"domain":"post-training","key":"opd-aha","title":"OPD-Aha: From Linguistic Momentum to Visual Reflection in Multimodal On-Policy Distillation","paper_url":"https://arxiv.org/abs/2609.16459","detail_path":"post-training/2609.16459-opd-aha/README.md","topic":["多模态后训练","On-policy distillation"],"first_author":"Chenhao Qiu","first_author_affiliation":"Arizona State University / University of Virginia / Stevens Institute of Technology","published":"2026-09-15","code":"https://github.com/Echochef/OPD-Aha","adapter":"opd-aha","priority":"P0"},
    {"domain":"post-training","key":"growmtp","title":"GrowMTP: Can RL Grow Its Own Draft Head?","paper_url":"https://arxiv.org/abs/2609.16648","detail_path":"post-training/2609.16648-growmtp/README.md","topic":["RL 训练加速","推测解码"],"first_author":"Minghua He","first_author_affiliation":"WeChat AI, Tencent / Peking University","published":"2026-09-15","code":None,"adapter":"growmtp","priority":"P1"},
    {"domain":"agent-research","key":"fuse-evaluator","title":"Verifiable Social Reasoning for LLM Assistants","paper_url":"https://arxiv.org/abs/2609.17496","detail_path":"agent-research/2609.17496-fuse-evaluator/README.md","topic":["Agent 评测","社会推理"],"first_author":"Amir Taubenfeld","first_author_affiliation":"Google Research / Hebrew University of Jerusalem / University of Cambridge","published":"2026-09-15","code":None,"adapter":"fuse-evaluator","priority":"P0"},
    {"domain":"agent-research","key":"harness-bandit","title":"HarnessBandit: Joint Learnability-Transferability Scheduling for Multi-Harness Agentic Reinforcement Learning","paper_url":"https://arxiv.org/abs/2609.13739","detail_path":"agent-research/2609.13739-harness-bandit/README.md","topic":["Agent RL","Harness 调度"],"first_author":"Hongliang Wei","first_author_affiliation":"Harbin Institute of Technology / Alibaba Cloud","published":"2026-09-12","code":None,"adapter":"harness-bandit","priority":"P1"},
    {"domain":"agent-research","key":"sciencebuddy","title":"ScienceBuddy: Recursive-in-Recursive Self-Improvement for Interactive Scientific Agents","paper_url":"https://arxiv.org/abs/2609.17523","detail_path":"agent-research/2609.17523-sciencebuddy/README.md","topic":["科学 Agent","递归自进化"],"first_author":"Shuhan Xue","first_author_affiliation":"Gen-Verse research collaboration","published":"2026-09-15","code":"https://github.com/Gen-Verse/ScienceBuddy","adapter":"sciencebuddy","priority":"P1"},
    {"domain":"foundation-models","key":"r4t","title":"Efficient, Property-Aligned Fan-Out Retrieval via RL-Compiled Diffusion","paper_url":"https://arxiv.org/abs/2603.06397","detail_path":"foundation-models/2603.06397-r4t/README.md","topic":["生成式检索","RL 编译"],"first_author":"Pengcheng Jiang","first_author_affiliation":"University of Illinois Urbana-Champaign / Google Research","published":"2026-03-06","code":None,"adapter":"r4t","priority":"P0"},
    {"domain":"foundation-models","key":"loopspec","title":"LoopSpec: Pipelined Self-Speculative Decoding for Looped Transformers","paper_url":"https://arxiv.org/abs/2609.17184","detail_path":"foundation-models/2609.17184-loopspec/README.md","topic":["推测解码","循环 Transformer"],"first_author":"SangLyul Cho","first_author_affiliation":"Seoul National University / KAIST","published":"2026-09-15","code":None,"adapter":"loopspec","priority":"P1"},
    {"domain":"foundation-models","key":"agentkv","title":"AgentKV: Phase-Aware KV Eviction for Agentic LLMs","paper_url":"https://arxiv.org/abs/2609.14872","detail_path":"foundation-models/2609.14872-agentkv/README.md","topic":["Agent 推理","KV Cache"],"first_author":"Taowen Tony Liu","first_author_affiliation":"University of Cambridge","published":"2026-09-14","code":"https://github.com/LiuTaowen-Tony/agentkv","adapter":"agentkv","priority":"P1"},
)
