"""Deprecated intake-batch view; edit paper_specs/catalog instead."""

from .paper_specs.catalog import legacy_records

LATEST_METHOD_PAPERS = legacy_records(
    (
        (
            ("foundation-models", "gemini-for-google"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("recommendation", "gear"),
            {
                "title": "Generative End-to-end Ad Retrieval at Douyin",
                "paper_url": "https://arxiv.org/abs/2609.39327",
                "topic": ["广告召回", "生成式检索", "语义 ID"],
                "published": "2026-09-30",
                "adapter": "gear",
                "priority": "P0",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "dars"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
                "upstream_note",
            ),
        ),
        (
            ("agent-research", "active-saddler"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "safe-self-improvement"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "range-grpo"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "veriharness"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("recommendation", "effective-training-time"),
            {
                "title": "Optimizing Effective Training Time for Large-Scale Recommendation Systems",
                "paper_url": "https://arxiv.org/abs/2610.02057",
                "topic": ["推荐训练系统", "训练有效时间", "GPU 集群"],
                "published": "2026-10-01",
                "adapter": "effective-training-time",
                "priority": "P1",
                "selection_exception": "用户于 2026-10-02 明确批准的生产训练基础设施例外；部署指标是 ETT，不作为推荐模型效果或线上 A/B 收益。",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
                "selection_exception",
            ),
        ),
        (
            ("foundation-models", "taco-optimizer"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
                "requires_gpu_validation",
                "gpu_validation_artifact",
            ),
        ),
        (
            ("foundation-models", "veto"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
                "requires_gpu_validation",
                "gpu_validation_artifact",
            ),
        ),
        (
            ("agent-research", "mem-plus-plus"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "defa"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "my-fault"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("agent-research", "flowright"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("post-training", "where-opd"),
            {},
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
            ),
        ),
        (
            ("recommendation", "gris"),
            {
                "title": "Neither Black nor White: Balancing Semantic and Collaborative Signals with Graph-Informed Semantic IDs (GrIS)",
                "paper_url": "https://arxiv.org/abs/2610.01533",
                "topic": ["生成式推荐", "语义 ID", "图聚类"],
                "published": "2026-10-01",
                "code": "https://github.com/hirc-airecs/graph-informed-sids",
                "adapter": "gris",
                "priority": "P1",
                "selection_exception": "用户于 2026-10-02 明确批准的学术/Evolve 机制例外；论文没有量化线上 A/B，不进入工业证据结论。",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
                "selection_exception",
            ),
        ),
        (
            ("recommendation", "repair-state"),
            {
                "title": "Not All Is Lost: Repairing Lossy User Preference States of Personalization Encoders",
                "paper_url": "https://arxiv.org/abs/2610.01270",
                "topic": ["个性化", "用户状态修复", "序列推荐"],
                "published": "2026-10-01",
                "adapter": "repair-state",
                "priority": "P1",
                "selection_exception": "用户于 2026-10-02 明确批准的学术/Evolve 机制例外；论文没有量化线上 A/B，不进入工业证据结论。",
            },
            (
                "domain",
                "key",
                "title",
                "paper_url",
                "detail_path",
                "topic",
                "first_author",
                "first_author_affiliation",
                "published",
                "code",
                "adapter",
                "priority",
                "selection_exception",
            ),
        ),
    )
)
