"""Reviewed P0/P1 metadata for the 2026-09-28 release window."""

LATEST_METHOD_PAPERS = (
    {
        "domain": "post-training", "key": "roft",
        "title": "Shockingly Simple Self-retrospection Improves Agentic Models Without RL",
        "paper_url": "https://arxiv.org/abs/2609.35741",
        "detail_path": "post-training/2609.35741-roft/README.md",
        "topic": ["自我回顾", "监督微调", "Agent 后训练"],
        "first_author": "Jonathan Light", "first_author_affiliation": "Rensselaer Polytechnic Institute",
        "published": "2026-09-28", "code": None, "adapter": "roft", "priority": "P0",
        "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/roft-a100-20260930.json",
    },
    {
        "domain": "post-training", "key": "lspd",
        "title": "An RL View of OPD: Least Square Policy Distillation for Sample-Efficient LLM Reasoning",
        "paper_url": "https://arxiv.org/abs/2609.35505",
        "detail_path": "post-training/2609.35505-lspd/README.md",
        "topic": ["On-policy distillation", "离策略回放", "推理"],
        "first_author": "Shangzhe Li", "first_author_affiliation": "University of North Carolina at Chapel Hill",
        "published": "2026-09-28", "code": "https://github.com/UNCSciML/LSPD", "adapter": "lspd", "priority": "P0",
        "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/lspd-a100-20260930.json",
    },
    {
        "domain": "agent-research", "key": "harness-learning",
        "title": "Harness Learning Enables Generalizable Test-Time Adaptation",
        "paper_url": "https://arxiv.org/abs/2609.35738",
        "detail_path": "agent-research/2609.35738-harness-learning/README.md",
        "topic": ["Harness 学习", "测试时适配", "元学习"],
        "first_author": "Alvin Zhang", "first_author_affiliation": "Johns Hopkins University",
        "published": "2026-09-28", "code": None, "adapter": "harness-learning", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "ms-gla",
        "title": "MS-GLA: Multi-Scale Gated Linear Attention for Addressing Representational Bottlenecks via Multi-Temporal Resolution",
        "paper_url": "https://arxiv.org/abs/2609.35664",
        "detail_path": "foundation-models/2609.35664-ms-gla/README.md",
        "topic": ["网络架构", "线性注意力", "长上下文"],
        "first_author": "Prasoon Dev", "first_author_affiliation": "International Institute of Information Technology Hyderabad",
        "published": "2026-09-28", "code": "https://github.com/prasoondev/msgla", "adapter": "ms-gla", "priority": "P1",
        "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/ms-gla-a100-20260930.json",
    },
    {
        "domain": "agent-research", "key": "graphhca",
        "title": "GraphHCA: Closed-Form Hindsight Credit Assignment for Long-Horizon LLM Agents",
        "paper_url": "https://arxiv.org/abs/2609.35084",
        "detail_path": "agent-research/2609.35084-graphhca/README.md",
        "topic": ["Agentic RL", "信用分配", "轨迹图"],
        "first_author": "Haodong Zhu", "first_author_affiliation": "Beihang University",
        "published": "2026-09-28", "code": None, "adapter": "graphhca", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "stepquant",
        "title": "STEPQuant: When and Where Errors Matter in Delta-Rule Recurrent State Quantization",
        "paper_url": "https://arxiv.org/abs/2609.38169",
        "detail_path": "foundation-models/2609.38169-stepquant/README.md",
        "topic": ["推理与系统效率", "线性注意力", "状态量化"],
        "first_author": "Bingchen Yao", "first_author_affiliation": "Zhejiang University",
        "published": "2026-09-29", "code": "https://github.com/Dreamer-Toby/STEPQuant",
        "adapter": "stepquant", "priority": "P1", "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/stepquant-a100-20260930.json",
    },
    {
        "domain": "foundation-models", "key": "leapquant",
        "title": "LeapQuant: Efficient Linear Attention with Accurate Recurrent State Quantization",
        "paper_url": "https://arxiv.org/abs/2609.38166",
        "detail_path": "foundation-models/2609.38166-leapquant/README.md",
        "topic": ["推理与系统效率", "线性注意力", "状态量化"],
        "first_author": "Yi Pan", "first_author_affiliation": "UC Berkeley",
        "published": "2026-09-29", "code": None, "adapter": "leapquant",
        "priority": "P1", "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/leapquant-a100-20260930.json",
    },
    {
        "domain": "foundation-models", "key": "chinese-jev",
        "title": "Chinese-Jev: Bringing System One Model to Chinese-Language Tasks",
        "paper_url": "https://arxiv.org/abs/2609.36965",
        "detail_path": "foundation-models/2609.36965-chinese-jev/README.md",
        "topic": ["System One / JEV", "中文理解", "高效决策模型"],
        "first_author": "Zexiao Wang", "first_author_affiliation": "Fudan University",
        "published": "2026-09-29", "code": "https://gulucaptain.github.io/Chinese-Jev/",
        "adapter": "chinese-jev", "priority": "P1",
    },
    {
        "domain": "post-training", "key": "dr-opd",
        "title": "Dr. OPD: Learning What to Follow for Optimal On-Policy Distillation of Large Language Models",
        "paper_url": "https://arxiv.org/abs/2609.38025",
        "detail_path": "post-training/2609.38025-dr-opd/README.md",
        "topic": ["On-policy distillation", "双层优化", "Token 权重"],
        "first_author": "Zhenyu Wang", "first_author_affiliation": "Rutgers University",
        "published": "2026-09-29", "code": "https://github.com/zywang0701/Dr-OPD",
        "adapter": "dr-opd", "priority": "P1", "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/dr-opd-a100-20260930.json",
    },
    {
        "domain": "post-training", "key": "sipo",
        "title": "SIPO: Unifying Reinforcement Learning with On-Policy Self-Distillation",
        "paper_url": "https://arxiv.org/abs/2609.36742",
        "detail_path": "post-training/2609.36742-sipo/README.md",
        "topic": ["RLVR", "On-policy self-distillation", "Token 信用分配"],
        "first_author": "Zhenrui Yue", "first_author_affiliation": "University of Illinois Urbana-Champaign",
        "published": "2026-09-29", "code": "https://github.com/Yueeeeeeee/SIPO",
        "adapter": "sipo", "priority": "P1", "requires_gpu_validation": True,
        "gpu_validation_artifact": "docs/gpu-validations/sipo-a100-20260930.json",
    },
    {
        "domain": "agent-research", "key": "remem",
        "title": "ReMem: Rethinking Perception and Memory in Long-Context Recommendation Agents",
        "paper_url": "https://arxiv.org/abs/2609.37311",
        "detail_path": "agent-research/2609.37311-remem/README.md",
        "topic": ["长期记忆", "推荐 Agent", "多模态感知"],
        "first_author": "Haohao Qu", "first_author_affiliation": "The Hong Kong Polytechnic University",
        "published": "2026-09-29", "code": "https://github.com/Quhaoh233/ReMem",
        "adapter": "remem", "priority": "P1",
    },
    {
        "domain": "agent-research", "key": "video-rsi",
        "title": "Video-RSI: Recursive Self-Improvement of Video Understanding Agents via Harness Evolution",
        "paper_url": "https://arxiv.org/abs/2609.37950",
        "detail_path": "agent-research/2609.37950-video-rsi/README.md",
        "topic": ["RSI", "Harness 演化", "视频理解 Agent"],
        "first_author": "Bingjun Luo", "first_author_affiliation": "Tsinghua University",
        "published": "2026-09-29", "code": "https://github.com/bingjunluo/Video-RSI",
        "adapter": "video-rsi", "priority": "P1",
    },
)
