"""Reviewed metadata for the implementation batch announced on 2026-09-11."""

LATEST_METHOD_PAPERS = (
    {
        "domain": "post-training", "key": "nsd",
        "title": "Negative Self-Distillation: Learning to Reason by Avoiding Flaws",
        "paper_url": "https://arxiv.org/abs/2609.11699",
        "detail_path": "post-training/2609.11699-nsd/README.md",
        "topic": ["负向自蒸馏", "推理后训练"], "first_author": "Rongcan Pei",
        "first_author_affiliation": "University of Virginia", "published": "2026-09-10",
        "code": "https://github.com/Prongcan/NSD", "adapter": "nsd", "priority": "P0",
    },
    {
        "domain": "post-training", "key": "adaptive-opd-gate",
        "title": "A Unified Per-Token Gating Family for On-Policy Distillation: FKL/RKL Mixing with Multi-Channel and Bias Coefficients",
        "paper_url": "https://arxiv.org/abs/2609.11768",
        "detail_path": "post-training/2609.11768-adaptive-opd-gate/README.md",
        "topic": ["On-policy distillation", "逐 token 自适应门控"], "first_author": "Suwan Wu",
        "first_author_affiliation": "Xiaohongshu", "published": "2026-09-10",
        "code": None, "adapter": "adaptive-opd-gate", "priority": "P1",
    },
    {
        "domain": "post-training", "key": "locus",
        "title": "LOCUS: Task-Aware Low-Rank Post-Training for Token-Efficient Language Generation",
        "paper_url": "https://arxiv.org/abs/2609.11739",
        "detail_path": "post-training/2609.11739-locus/README.md",
        "topic": ["低秩后训练", "Token 效率"], "first_author": "Dongfang Zhao",
        "first_author_affiliation": "University of Washington", "published": "2026-09-10",
        "code": None, "adapter": "locus", "priority": "P1",
    },
    {
        "domain": "post-training", "key": "tasco",
        "title": "Beyond Confidence: Stability-Aware Test-Time Adaptation for LLM Reasoning",
        "paper_url": "https://arxiv.org/abs/2609.11393",
        "detail_path": "post-training/2609.11393-tasco/README.md",
        "topic": ["测试时适配", "稳定性优化"], "first_author": "Bincheng Gu",
        "first_author_affiliation": "Chongqing University", "published": "2026-09-10",
        "code": None, "adapter": "tasco", "priority": "P1",
    },
    {
        "domain": "agent-research", "key": "cobra-skills",
        "title": "COBRA-Skills: Contextual Bandit-Guided Evolution for Agent Skill Optimization",
        "paper_url": "https://arxiv.org/abs/2609.11682",
        "detail_path": "agent-research/2609.11682-cobra-skills/README.md",
        "topic": ["技能进化", "Contextual bandit"], "first_author": "Pingchen Lu",
        "first_author_affiliation": "The Chinese University of Hong Kong, Shenzhen", "published": "2026-09-10",
        "code": "https://github.com/Jerry-LuP/COBRA-Skills", "adapter": "cobra-skills", "priority": "P0",
    },
    {
        "domain": "agent-research", "key": "ecdysis",
        "title": "Ecdysis: Efficient and Effective Training of Runtime Harnesses for LLM Agents",
        "paper_url": "https://arxiv.org/abs/2609.11677",
        "detail_path": "agent-research/2609.11677-ecdysis/README.md",
        "topic": ["Harness 自进化", "失败诊断"], "first_author": "Ruiqing Yue",
        "first_author_affiliation": "Chengdu Institute of Computer Applications, Chinese Academy of Sciences", "published": "2026-09-10",
        "code": "https://github.com/cuiyu-ai/Ecdysis", "adapter": "ecdysis", "priority": "P0",
    },
    {
        "domain": "agent-research", "key": "grounded-memory",
        "title": "Grounding Agent Memory: Environment-Probing Curation for Enterprise Agents",
        "paper_url": "https://arxiv.org/abs/2609.11060",
        "detail_path": "agent-research/2609.11060-grounded-memory/README.md",
        "topic": ["Agent 记忆", "环境探测"], "first_author": "Susheel Suresh",
        "first_author_affiliation": "Microsoft", "published": "2026-09-09",
        "code": None, "adapter": "grounded-memory", "priority": "P0",
    },
    {
        "domain": "agent-research", "key": "toolgrad",
        "title": "ToolGrad: Efficient Tool-Use Dataset Generation with Textual Gradients",
        "paper_url": "https://arxiv.org/abs/2508.04086",
        "detail_path": "agent-research/2508.04086-toolgrad/README.md",
        "topic": ["工具学习", "数据生成"], "first_author": "Zhongyi Zhou",
        "first_author_affiliation": "Google", "published": "2025-08-06",
        "code": "https://github.com/zhongyi-zhou/toolgrad", "adapter": "toolgrad", "priority": "P0",
    },
    {
        "domain": "agent-research", "key": "prompts",
        "title": "PROMPTS: Performance Optimization via Multi-Agent Planning for LLM Training and Serving",
        "paper_url": "https://research.google/pubs/prompts-performance-optimization-via-multi-agent-planning-for-llm-training-and-serving/",
        "detail_path": "agent-research/mlsys2026-prompts/README.md",
        "topic": ["训练服务优化", "多 Agent 性能诊断"], "first_author": "Yuran Ding",
        "first_author_affiliation": "University of Maryland / Google", "published": "2026-05-18",
        "code": None, "adapter": "prompts", "priority": "P0",
    },
    {
        "domain": "agent-research", "key": "searchatlas",
        "title": "SearchAtlas: Analyzing Agentic Search Strategies via Evidential Query Graphs",
        "paper_url": "https://arxiv.org/abs/2609.10901",
        "detail_path": "agent-research/2609.10901-searchatlas/README.md",
        "topic": ["搜索 Agent", "过程审计"], "first_author": "Jiacheng Sang",
        "first_author_affiliation": "Duke University", "published": "2026-09-09",
        "code": "https://github.com/DukeNLP/SearchAtlas", "adapter": "searchatlas", "priority": "P1",
    },
    {
        "domain": "agent-research", "key": "skill-retention",
        "title": "When Synthetic Data Hurts: On Catastrophic Forgetting in Skill Retrieval for LLM Agents",
        "paper_url": "https://arxiv.org/abs/2609.10750",
        "detail_path": "agent-research/2609.10750-skill-retention/README.md",
        "topic": ["技能检索", "灾难性遗忘"], "first_author": "Syed Shariyar Murtaza",
        "first_author_affiliation": "Manulife", "published": "2026-09-09",
        "code": "https://github.com/manulife-ai/emnlp2026/", "adapter": "skill-retention", "priority": "P1",
    },
    {
        "domain": "agent-research", "key": "t1-terminal-rl",
        "title": "T1: Terminal Agent Reinforcement Learning for Long-Horizon Tasks",
        "paper_url": "https://arxiv.org/abs/2609.11042",
        "detail_path": "agent-research/2609.11042-t1-terminal-rl/README.md",
        "topic": ["Agent RL", "长程终端任务"], "first_author": "Junyao Yang",
        "first_author_affiliation": "National University of Singapore / Tencent", "published": "2026-09-09",
        "code": None, "adapter": "t1-terminal-rl", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "omnikvquant",
        "title": "OmniKVQuant: KV Cache Quantization for Omni-LLMs",
        "paper_url": "https://arxiv.org/abs/2609.11582",
        "detail_path": "foundation-models/2609.11582-omnikvquant/README.md",
        "topic": ["多模态推理", "KV Cache 量化"], "first_author": "Suho Yoo",
        "first_author_affiliation": "KAIST", "published": "2026-09-10",
        "code": "https://github.com/kaistmm/OmniKVQuant", "adapter": "omnikvquant", "priority": "P0",
    },
    {
        "domain": "foundation-models", "key": "sensenova-u1-5",
        "title": "SenseNova-U1.5: Towards Native Unified Visual Intelligence",
        "paper_url": "https://arxiv.org/abs/2609.11929",
        "detail_path": "foundation-models/2609.11929-sensenova-u1-5/README.md",
        "topic": ["统一多模态", "视觉生成与理解"], "first_author": "SenseNova Team",
        "first_author_affiliation": "SenseTime Research", "published": "2026-09-10",
        "code": "https://github.com/OpenSenseNova/SenseNova-U1", "adapter": "sensenova-u1-5", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "frames-on-demand",
        "title": "Caption-once, Frames-on-Demand: Visual-Need Routing for Budget-Aware Agentic Long Video Understanding",
        "paper_url": "https://arxiv.org/abs/2609.11899",
        "detail_path": "foundation-models/2609.11899-frames-on-demand/README.md",
        "topic": ["长视频理解", "视觉预算路由"], "first_author": "Weitong Cai",
        "first_author_affiliation": "Queen Mary University of London", "published": "2026-09-10",
        "code": None, "adapter": "frames-on-demand", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "repeat-aware-moe",
        "title": "Data Scarcity and Model Sparsity: Mixtures-of-Experts Overfit More to Repeated Data",
        "paper_url": "https://arxiv.org/abs/2609.11917",
        "detail_path": "foundation-models/2609.11917-repeat-aware-moe/README.md",
        "topic": ["MoE", "数据重复与正则化"], "first_author": "Atindra Jha",
        "first_author_affiliation": "Stanford University", "published": "2026-09-10",
        "code": None, "adapter": "repeat-aware-moe", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "musec",
        "title": "Musec: MomentUm SpEctral Clipping for Stable Muon-type Training",
        "paper_url": "https://arxiv.org/abs/2609.11655",
        "detail_path": "foundation-models/2609.11655-musec/README.md",
        "topic": ["优化器", "谱裁剪"], "first_author": "Zhuanghua Liu",
        "first_author_affiliation": "National University of Singapore", "published": "2026-09-10",
        "code": None, "adapter": "musec", "priority": "P1",
    },
    {
        "domain": "foundation-models", "key": "swrouter",
        "title": "SWRouter: Similarity-Contractive Window Routing for Multi-Turn Large Language Model Conversations",
        "paper_url": "https://arxiv.org/abs/2609.11414",
        "detail_path": "foundation-models/2609.11414-swrouter/README.md",
        "topic": ["模型路由", "多轮上下文"], "first_author": "Yu Wang",
        "first_author_affiliation": "Shanghai Jiao Tong University", "published": "2026-09-10",
        "code": None, "adapter": "swrouter", "priority": "P1",
    },
)
